spring.application.name=property-rental-manager-backend

# Docker Compose uruchamiamy ręcznie z katalogu głównego projektu.
spring.docker.compose.enabled=false

server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/property_rental_manager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:property_rental_manager}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:local_development_password}