spring:
  application:
    name: property-rental-manager-backend
  docker:
    compose:
      enabled: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
